### ISSUE TITLE
On success finalPath return value is "undefined"

### ISSUE THREAD

**Issue by ben-praveen** [fuse-compound/Fuse.BackgroundDownload#2]
I am just trying to run the examples which you have provided with the module, But I am getting following in the console for success event, its not returning finalPath.

07-10 12:53:33.402 13390 13470 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
07-10 12:53:33.450 13390 13470 I OpenGLRenderer: Initialized EGL, version 1.4
07-10 12:53:35.935 13390 13390 D android.widget.GridLayout: vertical constraints: y1-y0>=600, y1-y0<=57 are inconsistent; permanently removing: y1-y0<=57.
07-10 12:53:38.230 13390 13426 I downloaddemo: Fcukeroo
07-10 12:53:38.232 13390 13426 I downloaddemo: Fcukeroo'd 1
07-10 12:53:40.107 13390 13426 I downloaddemo: succeeded
07-10 12:53:40.107 13390 13426 I downloaddemo: null
07-10 12:53:40.107 13390 13426 I downloaddemo: /data/user/0/com.apps.downloaddemo/cache/prefix829813709extension
07-10 12:53:40.108 13390 13426 I downloaddemo: 1
07-10 12:53:40.111 13390 13426 I downloaddemo: 1 - /data/user/0/com.apps.downloaddemo/cache/prefix829813709extension: undefined

**MainView.js**
`var Observable = require("FuseJS/Observable");
var Downloader = require("FuseJS/BackgroundDownload");

var lastDownloadID = -1;
var info = Observable("");

var startDownload = function() {
    console.log("Fcukeroo");
    // lastDownloadID = Downloader.start("http://i.imgur.com/F49TZOI.gif");
    lastDownloadID = Downloader.start("https://arjunphp.com/wp-content/uploads/2016/03/convert-pdf-jpeg-php.png");
    // lastDownloadID = Downloader.start("http://download.thinkbroadband.com/100MB.zip");
    console.log("Fcukeroo'd " + lastDownloadID);

    
};

var stopDownload = function() {
    console.log("stop called: " + lastDownloadID);
    Downloader.stop(lastDownloadID);
};

var pauseDownload = function() {
    console.log("pause called: " + lastDownloadID);
    Downloader.pause(lastDownloadID);
};

var resumeDownload = function() {
    console.log("resume called: " + lastDownloadID);
    lastDownloadID = Downloader.resume(lastDownloadID);
};

Downloader.on("progress", function(downloadID, bytesSoFar, totalBytesExpected) {
    console.log("Rock on " + downloadID + ": " + bytesSoFar/totalBytesExpected);
});

Downloader.on("paused", function(kind, downloadID) {
    console.log(kind + " - " + downloadID);
});

Downloader.on("succeeded", function(kind, downloadID, finalPath) {
    console.log("succeeded");
    console.log(finalPath);
    console.log(downloadID);
        console.log(kind);
    console.log(kind + " - " + downloadID + ": " + finalPath);
});

Downloader.on("failed", function(kind, downloadID, errorMessage) {
    console.log("failed");
    console.log(kind + " - " + downloadID + ": " + errorMessage);
});

module.exports = {
    startDownload: startDownload,
    stopDownload: stopDownload,
    pauseDownload: pauseDownload,
    resumeDownload: resumeDownload,
    info: info
};`

**MainView.ux**

`<App Background="#2586EC">
	<DockPanel>
		<JavaScript File="MainView.js"/>
		<StackPanel Dock="Top" Background="#2586EC">
			<StatusBarBackground/>
			<Fuse.iOS.StatusBarConfig Style="Light"/>
		</StackPanel>
		<BottomBarBackground Dock="Bottom" />

		<StackPanel Width="90%" Height="90%" Padding="20">
			<Rectangle Layer="Background" CornerRadius="10" Color="#fff"/>
			<Text Value="Download Test" Alignment="Center" FontSize="35" TextColor="#2586EC"/>

			<Button Text="Start Download" Clicked="{startDownload}" />
			<Button Text="Stop Download" Clicked="{stopDownload}" />
			<Button Text="Pause Download" Clicked="{pauseDownload}" />
			<Button Text="Resume Download" Clicked="{resumeDownload}" />

			<TextView Value="{info}" Height="200" TextWrapping="Wrap"/>
		</StackPanel>
	</DockPanel>
</App>`

**download-demo.unoproj**
`{
  "RootNamespace":"",
  "Packages": [
    "Fuse",
    "FuseJS"
  ],
  "Android": {
    "AllowBackup" : true
  },
  "Projects": [
    "./Fuse.BackgroundDownload/src/Fuse.BackgroundDownload.unoproj",
  ],
  "Includes": [
    "*"
  ]
}
`

**Comment by cbaggers** [comment]
Very odd, maybe it had issues with the latest release. I'll have a look.

**Comment by cbaggers** [comment]
Ah nope, turns out I had a silly mistake in the example. Fixed now :) 
Thanks for reporting!
